# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba23e23c82d6ca7fe08c79ce9a22979c"
name = "checkout-ui-ex"
handle = "checkput-ex"
application_url = "https://thin-antarctica-cached-cingular.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = ["https://thin-antarctica-cached-cingular.trycloudflare.com/auth/callback", "https://thin-antarctica-cached-cingular.trycloudflare.com/auth/shopify/callback", "https://thin-antarctica-cached-cingular.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
